/* config-keepassx.h. Generated by cmake from config-keepassx.h.cmake */

#ifndef KEEPASSX_CONFIG_KEEPASSX_H
#define KEEPASSX_CONFIG_KEEPASSX_H

#define KEEPASSXM_VERSION "@GIT_VERSION@"
#define GIT_HASH "@GIT_HASH@"

#cmakedefine WITH_XC_FDOSECRETS

#cmakedefine HAVE_PR_SET_DUMPABLE 1
#cmakedefine HAVE_RLIMIT_CORE 1

#endif // KEEPASSX_CONFIG_KEEPASSX_H
